[versions]
jetbrains-annotations = "26.0.2-1"
jspecify = "1.0.0"
dynamictooltiplib = "1.3.0"

[libraries]
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
dynamictooltiplib = { module = "org.herolias:DynamicTooltipsLib", version.ref = "dynamictooltiplib" }

[bundles]

[plugins]
